INFO:root:Test to standard out
ERROR:root:
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "C:\Users\arobins\Documents\GitHub\rs-backup-GUI\rs-backup-GUI.py", line 246, in <module>
ERROR:root:    raise Exception('Test to standard error')
ERROR:root:Exception: Test to standard error




INFO:root:
INFO:root:Backup running: PID is 10796
INFO:root:Running 14
INFO:root:Running 30
INFO:root:Waiting for backup thread to finish ....
INFO:root:Trying to kill backup ...
INFO:root:Trying to kill backup ...
INFO:root:Backup finished: elapsed time was: 58.9359998703
INFO:root:Exit code was: Not OK
INFO:root:Done!
INFO:root:Goodbye
ERROR:root:
ERROR:root:Traceback (most recent call last):
ERROR:root:** IDLE Internal Exception: 
ERROR:root:  File "C:\Python27\lib\idlelib\run.py", line 111, in main
ERROR:root:    seq, request = rpc.request_queue.get(block=True, timeout=0.05)
ERROR:root:  File "C:\Python27\lib\Queue.py", line 177, in get
ERROR:root:    self.not_empty.wait(remaining)
ERROR:root:  File "C:\Python27\lib\threading.py", line 359, in wait
ERROR:root:    _sleep(delay)
ERROR:root:TypeError: 'int' object is not callable
ERROR:root:
ERROR:root:Traceback (most recent call last):
ERROR:root:** IDLE Internal Exception: 
ERROR:root:  File "C:\Python27\lib\idlelib\run.py", line 111, in main
ERROR:root:    seq, request = rpc.request_queue.get(block=True, timeout=0.05)
ERROR:root:  File "C:\Python27\lib\Queue.py", line 177, in get
ERROR:root:    self.not_empty.wait(remaining)
ERROR:root:  File "C:\Python27\lib\threading.py", line 359, in wait
ERROR:root:    _sleep(delay)
ERROR:root:TypeError: 'int' object is not callable
ERROR:root:
ERROR:root:Traceback (most recent call last):
ERROR:root:** IDLE Internal Exception: 
ERROR:root:  File "C:\Python27\lib\idlelib\run.py", line 111, in main
ERROR:root:    seq, request = rpc.request_queue.get(block=True, timeout=0.05)
ERROR:root:  File "C:\Python27\lib\Queue.py", line 177, in get
ERROR:root:    self.not_empty.wait(remaining)
ERROR:root:  File "C:\Python27\lib\threading.py", line 359, in wait
ERROR:root:    _sleep(delay)
ERROR:root:TypeError: 'int' object is not callable
